// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNe30rn5LLcPFakRS-h-be8luHlIyz8BU',
    appId: '1:726128518998:web:a8aeb8219830603e07d8f7',
    messagingSenderId: '726128518998',
    projectId: 'navbat-ai',
    authDomain: 'navbat-ai.firebaseapp.com',
    storageBucket: 'navbat-ai.firebasestorage.app',
    measurementId: 'G-JPM6FGR1PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxNLKtwl3rHkcnoVg8aXmyDzPAGSIFHY',
    appId: '1:187755516216:android:5a4f08dc1f8e6a98f7f1cd',
    messagingSenderId: '187755516216',
    projectId: 'tiktok-b246c',
    storageBucket: 'tiktok-b246c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjmJP55UBfhj2nTzUdrq3cONHKo8vG1Hs',
    appId: '1:187755516216:ios:a35545c84a0db550f7f1cd',
    messagingSenderId: '187755516216',
    projectId: 'tiktok-b246c',
    storageBucket: 'tiktok-b246c.firebasestorage.app',
    iosBundleId: 'com.dasturchimobile.imtihon6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfJ96a4sv4wBmjdrX0gZzO-V8sDmSO538',
    appId: '1:726128518998:ios:b200b5b9a6e4de7407d8f7',
    messagingSenderId: '726128518998',
    projectId: 'navbat-ai',
    storageBucket: 'navbat-ai.firebasestorage.app',
    iosBundleId: 'com.dasturchimobile.imtihon6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNe30rn5LLcPFakRS-h-be8luHlIyz8BU',
    appId: '1:726128518998:web:09a97f557f2f4c9107d8f7',
    messagingSenderId: '726128518998',
    projectId: 'navbat-ai',
    authDomain: 'navbat-ai.firebaseapp.com',
    storageBucket: 'navbat-ai.firebasestorage.app',
    measurementId: 'G-QWEEM89C9W',
  );

}